{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $metadata := merge dict .Values.restapi.metadata (dict "labels" (fromYaml (include "slurm.labels" $))) -}}
{{- $podSpec := .Values.restapi.podSpec | default dict -}}
{{- $imagePullSecrets := concat list ($podSpec.imagePullSecrets | default list) (.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podSpec "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podSpec.priorityClassName | default (include "slurm.priorityClassName" . | toString) -}}
{{- $_ := set $podSpec "priorityClassName" $priorityClassName -}}
{{- $podTemplate := dict "metadata" $metadata "spec" $podSpec -}}
apiVersion: slinky.slurm.net/v1beta1
kind: RestApi
metadata:
  name: {{ include "slurm.fullname" . }}
  namespace: {{ include "slurm.namespace" . }}
{{- with $metadata }}
  {{- toYaml . | nindent 2 }}
{{- end }}{{- /* with $metadata */}}
spec:
  controllerRef:
    name: {{ include "slurm.fullname" . }}
    namespace: {{ include "slurm.namespace" . }}
  {{- with .Values.restapi.replicas }}
  replicas: {{ . }}
  {{- end }}{{- /* with .Values.restapi.replicas */}}
  slurmrestd:
    {{- $_ := set .Values.restapi.slurmrestd "imagePullPolicy" (get .Values.restapi.slurmrestd "imagePullPolicy" | default $.Values.imagePullPolicy ) -}}
    {{- include "format-container" .Values.restapi.slurmrestd | nindent 4 }}
  {{- include "format-podTemplate" $podTemplate | nindent 2 }}
  {{- with .Values.restapi.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with Values.restapi.service */}}
